//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უკაცრავად, ოპერაცია ვერ განხორციელდა..
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად წავშალო პასუხი?.
        /// </summary>
        public static string ConfirmDeleteAnswer {
            get {
                return ResourceManager.GetString("ConfirmDeleteAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად გნებავთ წიგნის წაშლა? ჩანაწერის წაშლა აგრეთვე გააქრობს მთელ მასზე დაბმულ სტატისტიკას..
        /// </summary>
        public static string ConfirmDeleteCourse {
            get {
                return ResourceManager.GetString("ConfirmDeleteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად გავწყვიტო კავშირი წიგნსა და გამოცდას შორის?.
        /// </summary>
        public static string ConfirmDeleteCourseQuiz {
            get {
                return ResourceManager.GetString("ConfirmDeleteCourseQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად გსურთ შეკითხვის წაშლა?.
        /// </summary>
        public static string ConfirmDeleteQuestion {
            get {
                return ResourceManager.GetString("ConfirmDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად წავშალო სურათი?.
        /// </summary>
        public static string ConfirmDeleteQuestionAsset {
            get {
                return ResourceManager.GetString("ConfirmDeleteQuestionAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად წავშალო ტესტი? ტესტი წაშლა გამოიწვევს ყველა მასზე დაბმული შეკითხვისა და პასუხის წაშლას..
        /// </summary>
        public static string ConfirmDeleteQuiz {
            get {
                return ResourceManager.GetString("ConfirmDeleteQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად გსურთ  გასაღების განახლება?.
        /// </summary>
        public static string ConfirmResetCourseKey {
            get {
                return ResourceManager.GetString("ConfirmResetCourseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ნამდვილად გნებავთ ჯგუფში ყველა გასაღების განახლება?.
        /// </summary>
        public static string ConfirmResetCourseKeyGroup {
            get {
                return ResourceManager.GetString("ConfirmResetCourseKeyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin cant be touched..
        /// </summary>
        public static string DontTouchMe {
            get {
                return ResourceManager.GetString("DontTouchMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გმადლობთ რეგისტრაციისათვის. თქვენი პროფილი წარმატებით დარეგისტრირდა. მისი გააქტიურებისათვის გთხოვთ მიჰყევით ქვედა ბმულს..
        /// </summary>
        public static string EmailTextRegistration {
            get {
                return ResourceManager.GetString("EmailTextRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy.
        /// </summary>
        public static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM yyyy.
        /// </summary>
        public static string FormatDateMonthYear {
            get {
                return ResourceManager.GetString("FormatDateMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yy.
        /// </summary>
        public static string FormatDateShortYear {
            get {
                return ResourceManager.GetString("FormatDateShortYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy hh:mm tt.
        /// </summary>
        public static string FormatDateTime {
            get {
                return ResourceManager.GetString("FormatDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fractal {0}.
        /// </summary>
        public static string FormatPageTitle {
            get {
                return ResourceManager.GetString("FormatPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quiz results..
        /// </summary>
        public static string InfoNoQuizResults {
            get {
                return ResourceManager.GetString("InfoNoQuizResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subscriptions..
        /// </summary>
        public static string InfoNoSubscriptions {
            get {
                return ResourceManager.GetString("InfoNoSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენს მიერ მითითებული ელ ფოსტა ჩვენს სისტემაში ვერ მოიძებნა..
        /// </summary>
        public static string InformationEmailNotInDB {
            get {
                return ResourceManager.GetString("InformationEmailNotInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to როგორც ჩანს თქვენ მოითხოვეთ პაროლის შეცვლა. მიჰყევით ბმულს თუ ნამდვილად გნებავთ გამოცვალოთ თქვენი პაროლი..
        /// </summary>
        public static string InformationPasswordReset {
            get {
                return ResourceManager.GetString("InformationPasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენ წარმატებით შეცვალეთ თქვენი პაროლი.
        /// </summary>
        public static string InformationPasswordUpdateSuccess {
            get {
                return ResourceManager.GetString("InformationPasswordUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენი პროფილი წარმატებით გააქტიურდა..
        /// </summary>
        public static string InformationProfileActivationSuccess {
            get {
                return ResourceManager.GetString("InformationProfileActivationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენ წარმატებით დარეგისტრირდით. გთოვთ შეამოწმოთ თქვენი ელ-ფოსტა პროფილის აქტივაციისათვის..
        /// </summary>
        public static string InformationRegistrationSuccess {
            get {
                return ResourceManager.GetString("InformationRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ეს გასაღები უკვე გამოყენებულია.
        /// </summary>
        public static string InformationUsedCourseKey {
            get {
                return ResourceManager.GetString("InformationUsedCourseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გასაღები ვერ მოიძებნა სისტემაში.
        /// </summary>
        public static string InvalidCourseKey {
            get {
                return ResourceManager.GetString("InvalidCourseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელ-ფოსტის ფორმატი არასწორია..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეტანილი პაროლი არ ემთხვევა მიმდინარე პაროლს..
        /// </summary>
        public static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to თქვენ არასწორად გაიმეორეთ პაროლი..
        /// </summary>
        public static string InvalidRePassword {
            get {
                return ResourceManager.GetString("InvalidRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to არასწორი მომხმარებელია ან პაროლი..
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$.
        /// </summary>
        public static string RegexEmail {
            get {
                return ResourceManager.GetString("RegexEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აუცილებელია წიგნის დასახელების შეყვანა.
        /// </summary>
        public static string RequiredCourseCaption {
            get {
                return ResourceManager.GetString("RequiredCourseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აუცილებელია ელ - ფოსტის შეყვანა..
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აუცილებელია დაწყების თარიღის შეყვანა..
        /// </summary>
        public static string RequiredEndDate {
            get {
                return ResourceManager.GetString("RequiredEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to სახელის შეყვანა აუცილებელია..
        /// </summary>
        public static string RequiredFirstName {
            get {
                return ResourceManager.GetString("RequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აუცილებელია პასუხების გამოქვეყნების თარიღის შეყვანა..
        /// </summary>
        public static string RequiredGradeDate {
            get {
                return ResourceManager.GetString("RequiredGradeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to გვარის შეყვანა აუცილებელია..
        /// </summary>
        public static string RequiredLastName {
            get {
                return ResourceManager.GetString("RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პაროლის შეყვანა აუცილებელია..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ტესტსის არჩევა აუცილებელია..
        /// </summary>
        public static string RequiredQuiz {
            get {
                return ResourceManager.GetString("RequiredQuiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აუცილებელია ტესტის დასახელების შეყვანა..
        /// </summary>
        public static string RequiredQuizCaption {
            get {
                return ResourceManager.GetString("RequiredQuizCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to აუცილებელია დასრულების თარიღის შეყვანა..
        /// </summary>
        public static string RequiredStartDate {
            get {
                return ResourceManager.GetString("RequiredStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to საწყისი თარიღი არ უნდა აღემატებოდეს დასასრულის თარიღს..
        /// </summary>
        public static string StartGreaterThanEnd {
            get {
                return ResourceManager.GetString("StartGreaterThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ცვლილებები წარმატებით შეინახა..
        /// </summary>
        public static string SuccessInformationSave {
            get {
                return ResourceManager.GetString("SuccessInformationSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ასეთი მისამართი უკვე გამოყენებულია, სცადეთ სხვა ფრაზა..
        /// </summary>
        public static string UniqCourseSlug {
            get {
                return ResourceManager.GetString("UniqCourseSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უკაცრავად, ეს ელ - ფოსტა უკვე დაკავებულია..
        /// </summary>
        public static string UniqEmail {
            get {
                return ResourceManager.GetString("UniqEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to უკაცრავად, ეს სახელი უკვე დაკავებულია.
        /// </summary>
        public static string UniqUsername {
            get {
                return ResourceManager.GetString("UniqUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to დასაშვებია მხოლოდ .jpg, .jpeg, .png or .gif ფორმატები..
        /// </summary>
        public static string WrongUploadedImageType {
            get {
                return ResourceManager.GetString("WrongUploadedImageType", resourceCulture);
            }
        }
    }
}
