#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Fractal")]
	public partial class DBCoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBCoreDataContext() : 
				base(global::DB.Properties.Settings.Default.FractalConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCourseDuration", IsComposable=true)]
		public System.Nullable<int> GetCourseDuration([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_dtAny", IsComposable=true)]
		public IQueryable<List_dtAnyResult> List_dtAny([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hrclvl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DCode", DbType="Int")] System.Nullable<int> dCode)
		{
			return this.CreateMethodCallQuery<List_dtAnyResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hrclvl, dCode);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleAnswer", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleAnswer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnswerID", DbType="BigInt")] System.Nullable<long> answerID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), answerID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleCourse", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleCourse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Slug", DbType="VarChar(50)")] string slug)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, courseID, slug).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleCourseKeyGroup", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleCourseKeyGroup([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupID", DbType="BigInt")] System.Nullable<long> groupID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleCourseQuiz", IsComposable=true)]
		public IQueryable<GetSingleCourseQuizResult> GetSingleCourseQuiz([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseQuizID", DbType="BigInt")] System.Nullable<long> courseQuizID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizID", DbType="BigInt")] System.Nullable<long> quizID)
		{
			return this.CreateMethodCallQuery<GetSingleCourseQuizResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseQuizID, courseID, quizID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleQuestion", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleQuestion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionID", DbType="BigInt")] System.Nullable<long> questionID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), questionID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleQuiz", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleQuiz([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), x).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_CourseKeys", IsComposable=true)]
		public IQueryable<List_CourseKeysResult> List_CourseKeys()
		{
			return this.CreateMethodCallQuery<List_CourseKeysResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_CourseKeysByGroupID", IsComposable=true)]
		public IQueryable<List_CourseKeysByGroupIDResult> List_CourseKeysByGroupID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupID", DbType="BigInt")] System.Nullable<long> groupID)
		{
			return this.CreateMethodCallQuery<List_CourseKeysByGroupIDResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), groupID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_CourseQuizes", IsComposable=true)]
		public IQueryable<List_CourseQuizesResult> List_CourseQuizes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPractice", DbType="Bit")] System.Nullable<bool> isPractice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConsiderDates", DbType="Bit")] System.Nullable<bool> considerDates, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SectionID", DbType="BigInt")] System.Nullable<long> sectionID)
		{
			return this.CreateMethodCallQuery<List_CourseQuizesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseID, isPublished, isPractice, considerDates, sectionID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_Quizes")]
		public int tx_Quizes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_Courses")]
		public int tx_Courses([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_Subscriptions")]
		public int tx_Subscriptions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_Tracking")]
		public int tx_Tracking([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsCourseSlugUniq", IsComposable=true)]
		public System.Nullable<bool> IsCourseSlugUniq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Slug", DbType="VarChar(50)")] string slug, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), slug, courseID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_CourseKeys")]
		public int tsp_CourseKeys([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyID", DbType="BigInt")] ref System.Nullable<long> keyID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupID", DbType="BigInt")] System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Key", DbType="VarChar(100)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, keyID, groupID, key);
			keyID = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_CourseKeyGroups")]
		public int tsp_CourseKeyGroups([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GroupID", DbType="BigInt")] ref System.Nullable<long> groupID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(100)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LifeTimeTypeID", DbType="Int")] System.Nullable<int> lifeTimeTypeID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MonthLifeTime", DbType="TinyInt")] System.Nullable<byte> monthLifeTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DayLifeTime", DbType="TinyInt")] System.Nullable<byte> dayLifeTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpDate", DbType="DateTime")] System.Nullable<System.DateTime> expDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, groupID, courseID, caption, lifeTimeTypeID, monthLifeTime, dayLifeTime, expDate);
			groupID = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_CourseKeys")]
		public int tx_CourseKeys([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_QuizAttempts", IsComposable=true)]
		public IQueryable<List_QuizAttemptsResult> List_QuizAttempts()
		{
			return this.CreateMethodCallQuery<List_QuizAttemptsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_Quizes", IsComposable=true)]
		public IQueryable<List_QuizesResult> List_Quizes()
		{
			return this.CreateMethodCallQuery<List_QuizesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_Answers")]
		public int tsp_Answers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AnswerID", DbType="BigInt")] ref System.Nullable<long> answerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionID", DbType="BigInt")] System.Nullable<long> questionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Answer", DbType="NVarChar(MAX)")] string answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Explanation", DbType="NVarChar(MAX)")] string explanation, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsCorrect", DbType="Bit")] System.Nullable<bool> isCorrect, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AssetID", DbType="BigInt")] System.Nullable<long> assetID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, answerID, questionID, answer, explanation, isCorrect, assetID);
			answerID = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_Questions")]
		public int tsp_Questions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionID", DbType="BigInt")] ref System.Nullable<long> questionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(MAX)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Hint", DbType="NVarChar(MAX)")] string hint, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Analysis", DbType="NVarChar(MAX)")] string analysis, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Score", DbType="Money")] System.Nullable<decimal> score, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AssetID", DbType="BigInt")] System.Nullable<long> assetID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, questionID, question, hint, analysis, score, isPublished, assetID);
			questionID = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_Answers", IsComposable=true)]
		public IQueryable<List_AnswersResult> List_Answers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionID", DbType="BigInt")] System.Nullable<long> questionID)
		{
			return this.CreateMethodCallQuery<List_AnswersResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), questionID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_Answers")]
		public int tx_Answers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_Questions")]
		public int tx_Questions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_Quizes")]
		public int tsp_Quizes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizID", DbType="BigInt")] ref System.Nullable<long> quizID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(200)")] string caption)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, quizID, caption);
			quizID = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_CourseQuizes")]
		public int tsp_CourseQuizes([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecordID", DbType="BigInt")] System.Nullable<long> recordID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizID", DbType="BigInt")] System.Nullable<long> quizID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="DateTime")] System.Nullable<System.DateTime> startDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="DateTime")] System.Nullable<System.DateTime> endDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GradeReleaseDate", DbType="DateTime")] System.Nullable<System.DateTime> gradeReleaseDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPractice", DbType="Bit")] System.Nullable<bool> isPractice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SectionID", DbType="BigInt")] System.Nullable<long> sectionID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, recordID, courseID, quizID, startDate, endDate, gradeReleaseDate, isPublished, isPractice, sectionID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsUserAlreadyPassedQuiz", IsComposable=true)]
		public System.Nullable<bool> IsUserAlreadyPassedQuiz([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizID", DbType="BigInt")] System.Nullable<long> quizID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, quizID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_UserQuizes", IsComposable=true)]
		public IQueryable<List_UserQuizesResult> List_UserQuizes()
		{
			return this.CreateMethodCallQuery<List_UserQuizesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_TeacherQuizesNotInCourse", IsComposable=true)]
		public IQueryable<List_TeacherQuizesNotInCourseResult> List_TeacherQuizesNotInCourse([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID)
		{
			return this.CreateMethodCallQuery<List_TeacherQuizesNotInCourseResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, courseID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_TeacherQuizes", IsComposable=true)]
		public IQueryable<List_TeacherQuizesResult> List_TeacherQuizes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID)
		{
			return this.CreateMethodCallQuery<List_TeacherQuizesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_dtAny", IsComposable=true)]
		public object tsp_dtAny(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> codeid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mgrid, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string hname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string hnamee, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string hcode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> dcode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> defval, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Money")] System.Nullable<decimal> vm1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortVal", DbType="Int")] System.Nullable<int> sortVal, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string img1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string img2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string img3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string img4, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string img5, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string img6, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IntCode", DbType="Int")] System.Nullable<int> intCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, codeid, mgrid, hname, hnamee, hcode, dcode, defval, vm1, sortVal, img1, img2, img3, img4, img5, img6, intCode);
			codeid = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((object)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_Assets")]
		public int tx_Assets([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleAsset", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleAsset([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AssetID", DbType="BigInt")] System.Nullable<long> assetID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IncludeStatistics", DbType="Bit")] System.Nullable<bool> includeStatistics)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), assetID, includeStatistics).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_Courses")]
		public int tsp_Courses([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] ref System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(500)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="NVarChar(MAX)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubjectID", DbType="Int")] System.Nullable<int> subjectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Icon", DbType="NVarChar(500)")] string icon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PromoImage", DbType="NVarChar(100)")] string promoImage, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SemesterID", DbType="Int")] System.Nullable<int> semesterID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Year", DbType="SmallInt")] System.Nullable<short> year, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Slug", DbType="VarChar(100)")] string slug)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, courseID, caption, description, subjectID, icon, promoImage, semesterID, year, isPublished, slug);
			courseID = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_Courses", IsComposable=true)]
		public IQueryable<List_CoursesResult> List_Courses()
		{
			return this.CreateMethodCallQuery<List_CoursesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_UserCourses", IsComposable=true)]
		public IQueryable<List_UserCoursesResult> List_UserCourses([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			return this.CreateMethodCallQuery<List_UserCoursesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, isPublished);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_CourseKeyGroups", IsComposable=true)]
		public IQueryable<List_CourseKeyGroupsResult> List_CourseKeyGroups([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID)
		{
			return this.CreateMethodCallQuery<List_CourseKeyGroupsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_UserQuestionsNotInQuiz", IsComposable=true)]
		public IQueryable<List_UserQuestionsNotInQuizResult> List_UserQuestionsNotInQuiz([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuizID", DbType="BigInt")] System.Nullable<long> quizID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyWords", DbType="NVarChar(4000)")] string keyWords)
		{
			return this.CreateMethodCallQuery<List_UserQuestionsNotInQuizResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, quizID, keyWords);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCourseCreatorUserID", IsComposable=true)]
		public System.Nullable<long> GetCourseCreatorUserID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID)
		{
			return ((System.Nullable<long>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteCourse")]
		public int DeleteCourse([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_CourseQuizzesWithUserResults", IsComposable=true)]
		public IQueryable<List_CourseQuizzesWithUserResultsResult> List_CourseQuizzesWithUserResults([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID)
		{
			return this.CreateMethodCallQuery<List_CourseQuizzesWithUserResultsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), courseID, userID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_UserSubscribedCourses", IsComposable=true)]
		public IQueryable<List_UserSubscribedCoursesResult> List_UserSubscribedCourses([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ActiveOnly", DbType="Bit")] System.Nullable<bool> activeOnly)
		{
			return this.CreateMethodCallQuery<List_UserSubscribedCoursesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, activeOnly);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_QuizzesAllowedForUser", IsComposable=true)]
		public IQueryable<List_QuizzesAllowedForUserResult> List_QuizzesAllowedForUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID)
		{
			return this.CreateMethodCallQuery<List_QuizzesAllowedForUserResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_UserCourseSubscriptionHistory", IsComposable=true)]
		public IQueryable<List_UserCourseSubscriptionHistoryResult> List_UserCourseSubscriptionHistory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID)
		{
			return this.CreateMethodCallQuery<List_UserCourseSubscriptionHistoryResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, courseID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_UserCourseRecentSubscriptions", IsComposable=true)]
		public IQueryable<List_UserCourseRecentSubscriptionsResult> List_UserCourseRecentSubscriptions()
		{
			return this.CreateMethodCallQuery<List_UserCourseRecentSubscriptionsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_Subscriptions")]
		public int tsp_Subscriptions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubscriptionID", DbType="BigInt")] System.Nullable<long> subscriptionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseID", DbType="BigInt")] System.Nullable<long> courseID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeCode", DbType="NVarChar(200)")] string typeCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TariffID", DbType="BigInt")] System.Nullable<long> tariffID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpDate", DbType="DateTime")] System.Nullable<System.DateTime> expDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Note", DbType="NVarChar(400)")] string note)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, subscriptionID, userID, courseID, typeCode, type, tariffID, expDate, note);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class List_dtAnyResult
	{
		
		private int _codeid;
		
		private string _hname;
		
		private string _hnamee;
		
		private System.Nullable<int> _mgrid;
		
		private System.Nullable<short> _hrclvl;
		
		private string _hrccrt;
		
		private string _hcode;
		
		private System.Nullable<short> _dcode;
		
		private bool _defval;
		
		private System.Nullable<System.DateTime> _crtime;
		
		private decimal _vm1;
		
		private System.Nullable<int> _SortVal;
		
		private string _img1;
		
		private string _img2;
		
		private string _img3;
		
		private string _img4;
		
		private string _img5;
		
		private string _img6;
		
		private System.Nullable<int> _IntCode;
		
		private System.Nullable<int> _OldID;
		
		public List_dtAnyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeid", DbType="Int NOT NULL")]
		public int codeid
		{
			get
			{
				return this._codeid;
			}
			set
			{
				if ((this._codeid != value))
				{
					this._codeid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hname", DbType="NVarChar(200)")]
		public string hname
		{
			get
			{
				return this._hname;
			}
			set
			{
				if ((this._hname != value))
				{
					this._hname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hnamee", DbType="NVarChar(200)")]
		public string hnamee
		{
			get
			{
				return this._hnamee;
			}
			set
			{
				if ((this._hnamee != value))
				{
					this._hnamee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mgrid", DbType="Int")]
		public System.Nullable<int> mgrid
		{
			get
			{
				return this._mgrid;
			}
			set
			{
				if ((this._mgrid != value))
				{
					this._mgrid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrclvl", DbType="SmallInt")]
		public System.Nullable<short> hrclvl
		{
			get
			{
				return this._hrclvl;
			}
			set
			{
				if ((this._hrclvl != value))
				{
					this._hrclvl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hrccrt", DbType="VarChar(120)")]
		public string hrccrt
		{
			get
			{
				return this._hrccrt;
			}
			set
			{
				if ((this._hrccrt != value))
				{
					this._hrccrt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hcode", DbType="NVarChar(200)")]
		public string hcode
		{
			get
			{
				return this._hcode;
			}
			set
			{
				if ((this._hcode != value))
				{
					this._hcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dcode", DbType="SmallInt")]
		public System.Nullable<short> dcode
		{
			get
			{
				return this._dcode;
			}
			set
			{
				if ((this._dcode != value))
				{
					this._dcode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_defval", DbType="Bit NOT NULL")]
		public bool defval
		{
			get
			{
				return this._defval;
			}
			set
			{
				if ((this._defval != value))
				{
					this._defval = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_crtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> crtime
		{
			get
			{
				return this._crtime;
			}
			set
			{
				if ((this._crtime != value))
				{
					this._crtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vm1", DbType="Money NOT NULL")]
		public decimal vm1
		{
			get
			{
				return this._vm1;
			}
			set
			{
				if ((this._vm1 != value))
				{
					this._vm1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortVal", DbType="Int")]
		public System.Nullable<int> SortVal
		{
			get
			{
				return this._SortVal;
			}
			set
			{
				if ((this._SortVal != value))
				{
					this._SortVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img1", DbType="NVarChar(200)")]
		public string img1
		{
			get
			{
				return this._img1;
			}
			set
			{
				if ((this._img1 != value))
				{
					this._img1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img2", DbType="NVarChar(200)")]
		public string img2
		{
			get
			{
				return this._img2;
			}
			set
			{
				if ((this._img2 != value))
				{
					this._img2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img3", DbType="NVarChar(200)")]
		public string img3
		{
			get
			{
				return this._img3;
			}
			set
			{
				if ((this._img3 != value))
				{
					this._img3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img4", DbType="NVarChar(200)")]
		public string img4
		{
			get
			{
				return this._img4;
			}
			set
			{
				if ((this._img4 != value))
				{
					this._img4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img5", DbType="NVarChar(200)")]
		public string img5
		{
			get
			{
				return this._img5;
			}
			set
			{
				if ((this._img5 != value))
				{
					this._img5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img6", DbType="NVarChar(200)")]
		public string img6
		{
			get
			{
				return this._img6;
			}
			set
			{
				if ((this._img6 != value))
				{
					this._img6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntCode", DbType="Int")]
		public System.Nullable<int> IntCode
		{
			get
			{
				return this._IntCode;
			}
			set
			{
				if ((this._IntCode != value))
				{
					this._IntCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OldID", DbType="Int")]
		public System.Nullable<int> OldID
		{
			get
			{
				return this._OldID;
			}
			set
			{
				if ((this._OldID != value))
				{
					this._OldID = value;
				}
			}
		}
	}
	
	public partial class GetSingleCourseQuizResult
	{
		
		private long _RecordID;
		
		private long _CourseID;
		
		private long _QuizID;
		
		private string _QuizCaption;
		
		private string _CourseCaption;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<System.DateTime> _GradeReleaseDate;
		
		private bool _IsPublished;
		
		private bool _IsPractice;
		
		private bool _ShowAnswers;
		
		private decimal _MinScore;
		
		private string _unid;
		
		private System.DateTime _CRTime;
		
		private System.Nullable<long> _SectionID;
		
		public GetSingleCourseQuizResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="BigInt NOT NULL")]
		public long RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt NOT NULL")]
		public long QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizCaption", DbType="NVarChar(100)")]
		public string QuizCaption
		{
			get
			{
				return this._QuizCaption;
			}
			set
			{
				if ((this._QuizCaption != value))
				{
					this._QuizCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseCaption", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string CourseCaption
		{
			get
			{
				return this._CourseCaption;
			}
			set
			{
				if ((this._CourseCaption != value))
				{
					this._CourseCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeReleaseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GradeReleaseDate
		{
			get
			{
				return this._GradeReleaseDate;
			}
			set
			{
				if ((this._GradeReleaseDate != value))
				{
					this._GradeReleaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPractice", DbType="Bit NOT NULL")]
		public bool IsPractice
		{
			get
			{
				return this._IsPractice;
			}
			set
			{
				if ((this._IsPractice != value))
				{
					this._IsPractice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowAnswers", DbType="Bit NOT NULL")]
		public bool ShowAnswers
		{
			get
			{
				return this._ShowAnswers;
			}
			set
			{
				if ((this._ShowAnswers != value))
				{
					this._ShowAnswers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinScore", DbType="Money NOT NULL")]
		public decimal MinScore
		{
			get
			{
				return this._MinScore;
			}
			set
			{
				if ((this._MinScore != value))
				{
					this._MinScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unid", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string unid
		{
			get
			{
				return this._unid;
			}
			set
			{
				if ((this._unid != value))
				{
					this._unid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionID", DbType="BigInt")]
		public System.Nullable<long> SectionID
		{
			get
			{
				return this._SectionID;
			}
			set
			{
				if ((this._SectionID != value))
				{
					this._SectionID = value;
				}
			}
		}
	}
	
	public partial class List_CourseKeysResult
	{
		
		private long _KeyID;
		
		private long _GroupID;
		
		private string _Group;
		
		private string _Key;
		
		private byte _MonthLifeTime;
		
		private System.DateTime _RegTime;
		
		private long _CourseID;
		
		private string _Course;
		
		private System.Nullable<long> _UserID;
		
		private System.Nullable<System.DateTime> _UseTime;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		public List_CourseKeysResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyID", DbType="BigInt NOT NULL")]
		public long KeyID
		{
			get
			{
				return this._KeyID;
			}
			set
			{
				if ((this._KeyID != value))
				{
					this._KeyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="BigInt NOT NULL")]
		public long GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this._GroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this._Group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthLifeTime", DbType="TinyInt NOT NULL")]
		public byte MonthLifeTime
		{
			get
			{
				return this._MonthLifeTime;
			}
			set
			{
				if ((this._MonthLifeTime != value))
				{
					this._MonthLifeTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegTime", DbType="DateTime NOT NULL")]
		public System.DateTime RegTime
		{
			get
			{
				return this._RegTime;
			}
			set
			{
				if ((this._RegTime != value))
				{
					this._RegTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt")]
		public System.Nullable<long> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UseTime
		{
			get
			{
				return this._UseTime;
			}
			set
			{
				if ((this._UseTime != value))
				{
					this._UseTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
	}
	
	public partial class List_CourseKeysByGroupIDResult
	{
		
		private long _KeyID;
		
		private string _Key;
		
		private System.Nullable<long> _UserID;
		
		private System.Nullable<System.DateTime> _UseTime;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		public List_CourseKeysByGroupIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyID", DbType="BigInt NOT NULL")]
		public long KeyID
		{
			get
			{
				return this._KeyID;
			}
			set
			{
				if ((this._KeyID != value))
				{
					this._KeyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this._Key = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt")]
		public System.Nullable<long> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> UseTime
		{
			get
			{
				return this._UseTime;
			}
			set
			{
				if ((this._UseTime != value))
				{
					this._UseTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
	}
	
	public partial class List_CourseQuizesResult
	{
		
		private long _RecordID;
		
		private long _QuizID;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<System.DateTime> _GradeReleaseDate;
		
		private bool _IsPublished;
		
		private bool _IsPractice;
		
		private bool _ShowAnswers;
		
		private string _unid;
		
		private System.DateTime _CRTime;
		
		private string _Caption;
		
		private System.Nullable<long> _SectionID;
		
		private string _Section;
		
		private System.Nullable<decimal> _MaxScore;
		
		public List_CourseQuizesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="BigInt NOT NULL")]
		public long RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt NOT NULL")]
		public long QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeReleaseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GradeReleaseDate
		{
			get
			{
				return this._GradeReleaseDate;
			}
			set
			{
				if ((this._GradeReleaseDate != value))
				{
					this._GradeReleaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPractice", DbType="Bit NOT NULL")]
		public bool IsPractice
		{
			get
			{
				return this._IsPractice;
			}
			set
			{
				if ((this._IsPractice != value))
				{
					this._IsPractice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowAnswers", DbType="Bit NOT NULL")]
		public bool ShowAnswers
		{
			get
			{
				return this._ShowAnswers;
			}
			set
			{
				if ((this._ShowAnswers != value))
				{
					this._ShowAnswers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unid", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string unid
		{
			get
			{
				return this._unid;
			}
			set
			{
				if ((this._unid != value))
				{
					this._unid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SectionID", DbType="BigInt")]
		public System.Nullable<long> SectionID
		{
			get
			{
				return this._SectionID;
			}
			set
			{
				if ((this._SectionID != value))
				{
					this._SectionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Section", DbType="NVarChar(200)")]
		public string Section
		{
			get
			{
				return this._Section;
			}
			set
			{
				if ((this._Section != value))
				{
					this._Section = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Money")]
		public System.Nullable<decimal> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
	}
	
	public partial class List_QuizAttemptsResult
	{
		
		private long _AttemptID;
		
		private System.Nullable<byte> _Num;
		
		private long _UserID;
		
		private System.Nullable<long> _QuizID;
		
		private System.Nullable<long> _CourseID;
		
		private string _CourseCaption;
		
		private System.Nullable<short> _CourseYear;
		
		private System.Nullable<decimal> _Score;
		
		private System.Nullable<int> _Status;
		
		private System.DateTime _CRTime;
		
		private string _QuizCaption;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<System.DateTime> _GradeReleaseDate;
		
		private bool _IsPublished;
		
		private System.Nullable<bool> _ShowAnswers;
		
		private System.Nullable<decimal> _MinScore;
		
		private string _Username;
		
		private string _UserFullName;
		
		private System.Nullable<decimal> _MaxScore;
		
		public List_QuizAttemptsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttemptID", DbType="BigInt NOT NULL")]
		public long AttemptID
		{
			get
			{
				return this._AttemptID;
			}
			set
			{
				if ((this._AttemptID != value))
				{
					this._AttemptID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num", DbType="TinyInt")]
		public System.Nullable<byte> Num
		{
			get
			{
				return this._Num;
			}
			set
			{
				if ((this._Num != value))
				{
					this._Num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt NOT NULL")]
		public long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt")]
		public System.Nullable<long> QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt")]
		public System.Nullable<long> CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseCaption", DbType="NVarChar(500)")]
		public string CourseCaption
		{
			get
			{
				return this._CourseCaption;
			}
			set
			{
				if ((this._CourseCaption != value))
				{
					this._CourseCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseYear", DbType="SmallInt")]
		public System.Nullable<short> CourseYear
		{
			get
			{
				return this._CourseYear;
			}
			set
			{
				if ((this._CourseYear != value))
				{
					this._CourseYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this._Score = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizCaption", DbType="NVarChar(100)")]
		public string QuizCaption
		{
			get
			{
				return this._QuizCaption;
			}
			set
			{
				if ((this._QuizCaption != value))
				{
					this._QuizCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeReleaseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> GradeReleaseDate
		{
			get
			{
				return this._GradeReleaseDate;
			}
			set
			{
				if ((this._GradeReleaseDate != value))
				{
					this._GradeReleaseDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowAnswers", DbType="Bit")]
		public System.Nullable<bool> ShowAnswers
		{
			get
			{
				return this._ShowAnswers;
			}
			set
			{
				if ((this._ShowAnswers != value))
				{
					this._ShowAnswers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinScore", DbType="Money")]
		public System.Nullable<decimal> MinScore
		{
			get
			{
				return this._MinScore;
			}
			set
			{
				if ((this._MinScore != value))
				{
					this._MinScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFullName", DbType="NVarChar(401)")]
		public string UserFullName
		{
			get
			{
				return this._UserFullName;
			}
			set
			{
				if ((this._UserFullName != value))
				{
					this._UserFullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Money")]
		public System.Nullable<decimal> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
	}
	
	public partial class List_QuizesResult
	{
		
		private long _QuizID;
		
		private string _Caption;
		
		private System.DateTime _CRTime;
		
		private System.Nullable<long> _UserID;
		
		private System.Nullable<bool> _IsCreator;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		public List_QuizesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt NOT NULL")]
		public long QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt")]
		public System.Nullable<long> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCreator", DbType="Bit")]
		public System.Nullable<bool> IsCreator
		{
			get
			{
				return this._IsCreator;
			}
			set
			{
				if ((this._IsCreator != value))
				{
					this._IsCreator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
	}
	
	public partial class List_AnswersResult
	{
		
		private long _AnswerID;
		
		private long _QuestionID;
		
		private string _Answer;
		
		private string _Explanation;
		
		private bool _IsCorrect;
		
		private System.Guid _unid;
		
		private System.DateTime _CRTime;
		
		public List_AnswersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnswerID", DbType="BigInt NOT NULL")]
		public long AnswerID
		{
			get
			{
				return this._AnswerID;
			}
			set
			{
				if ((this._AnswerID != value))
				{
					this._AnswerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", DbType="BigInt NOT NULL")]
		public long QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					this._QuestionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this._Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Explanation", DbType="NVarChar(MAX)")]
		public string Explanation
		{
			get
			{
				return this._Explanation;
			}
			set
			{
				if ((this._Explanation != value))
				{
					this._Explanation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCorrect", DbType="Bit NOT NULL")]
		public bool IsCorrect
		{
			get
			{
				return this._IsCorrect;
			}
			set
			{
				if ((this._IsCorrect != value))
				{
					this._IsCorrect = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid unid
		{
			get
			{
				return this._unid;
			}
			set
			{
				if ((this._unid != value))
				{
					this._unid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_UserQuizesResult
	{
		
		private long _RecordID;
		
		private System.Nullable<long> _QuizID;
		
		private string _Caption;
		
		private System.Nullable<long> _UserID;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		private bool _IsCreator;
		
		private bool _View;
		
		private bool _Edit;
		
		private bool _Delete;
		
		private System.DateTime _CRTime;
		
		public List_UserQuizesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="BigInt NOT NULL")]
		public long RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt")]
		public System.Nullable<long> QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt")]
		public System.Nullable<long> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCreator", DbType="Bit NOT NULL")]
		public bool IsCreator
		{
			get
			{
				return this._IsCreator;
			}
			set
			{
				if ((this._IsCreator != value))
				{
					this._IsCreator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[View]", Storage="_View", DbType="Bit NOT NULL")]
		public bool View
		{
			get
			{
				return this._View;
			}
			set
			{
				if ((this._View != value))
				{
					this._View = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edit", DbType="Bit NOT NULL")]
		public bool Edit
		{
			get
			{
				return this._Edit;
			}
			set
			{
				if ((this._Edit != value))
				{
					this._Edit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Delete]", Storage="_Delete", DbType="Bit NOT NULL")]
		public bool Delete
		{
			get
			{
				return this._Delete;
			}
			set
			{
				if ((this._Delete != value))
				{
					this._Delete = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_TeacherQuizesNotInCourseResult
	{
		
		private System.Nullable<long> _QuizID;
		
		private string _Caption;
		
		private System.DateTime _CRTime;
		
		public List_TeacherQuizesNotInCourseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt")]
		public System.Nullable<long> QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_TeacherQuizesResult
	{
		
		private System.Nullable<long> _QuizID;
		
		private string _Caption;
		
		private System.DateTime _CRTime;
		
		private System.Nullable<int> _QuestionCount;
		
		public List_TeacherQuizesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt")]
		public System.Nullable<long> QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionCount", DbType="Int")]
		public System.Nullable<int> QuestionCount
		{
			get
			{
				return this._QuestionCount;
			}
			set
			{
				if ((this._QuestionCount != value))
				{
					this._QuestionCount = value;
				}
			}
		}
	}
	
	public partial class List_CoursesResult
	{
		
		private long _CourseID;
		
		private string _Slug;
		
		private string _Caption;
		
		private string _Description;
		
		private System.Nullable<int> _SubjectID;
		
		private string _Icon;
		
		private System.Nullable<int> _SemesterID;
		
		private System.Nullable<short> _Year;
		
		private bool _IsPublished;
		
		private System.DateTime _CRTime;
		
		public List_CoursesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slug", DbType="VarChar(100)")]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this._Slug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int")]
		public System.Nullable<int> SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(500)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this._Icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SemesterID", DbType="Int")]
		public System.Nullable<int> SemesterID
		{
			get
			{
				return this._SemesterID;
			}
			set
			{
				if ((this._SemesterID != value))
				{
					this._SemesterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="SmallInt")]
		public System.Nullable<short> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_UserCoursesResult
	{
		
		private long _RecordID;
		
		private long _UserID;
		
		private long _CourseID;
		
		private bool _IsCreator;
		
		private System.DateTime _CRTime;
		
		private string _Caption;
		
		private string _Slug;
		
		private string _Description;
		
		private string _Author;
		
		private string _Icon;
		
		private System.Nullable<int> _SubjectID;
		
		private System.Nullable<short> _Year;
		
		private System.Nullable<int> _SemesterID;
		
		private bool _IsPublished;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		private string _Semester;
		
		public List_UserCoursesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="BigInt NOT NULL")]
		public long RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt NOT NULL")]
		public long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCreator", DbType="Bit NOT NULL")]
		public bool IsCreator
		{
			get
			{
				return this._IsCreator;
			}
			set
			{
				if ((this._IsCreator != value))
				{
					this._IsCreator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slug", DbType="VarChar(100)")]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this._Slug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(100)")]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this._Author = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(500)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this._Icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubjectID", DbType="Int")]
		public System.Nullable<int> SubjectID
		{
			get
			{
				return this._SubjectID;
			}
			set
			{
				if ((this._SubjectID != value))
				{
					this._SubjectID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="SmallInt")]
		public System.Nullable<short> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SemesterID", DbType="Int")]
		public System.Nullable<int> SemesterID
		{
			get
			{
				return this._SemesterID;
			}
			set
			{
				if ((this._SemesterID != value))
				{
					this._SemesterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Semester", DbType="NVarChar(200)")]
		public string Semester
		{
			get
			{
				return this._Semester;
			}
			set
			{
				if ((this._Semester != value))
				{
					this._Semester = value;
				}
			}
		}
	}
	
	public partial class List_CourseKeyGroupsResult
	{
		
		private long _GroupID;
		
		private string _Group;
		
		private System.DateTime _CRTime;
		
		private int _KeyCount;
		
		private byte _MonthLifeTime;
		
		public List_CourseKeyGroupsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="BigInt NOT NULL")]
		public long GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this._GroupID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Group]", Storage="_Group", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Group
		{
			get
			{
				return this._Group;
			}
			set
			{
				if ((this._Group != value))
				{
					this._Group = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyCount", DbType="Int NOT NULL")]
		public int KeyCount
		{
			get
			{
				return this._KeyCount;
			}
			set
			{
				if ((this._KeyCount != value))
				{
					this._KeyCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonthLifeTime", DbType="TinyInt NOT NULL")]
		public byte MonthLifeTime
		{
			get
			{
				return this._MonthLifeTime;
			}
			set
			{
				if ((this._MonthLifeTime != value))
				{
					this._MonthLifeTime = value;
				}
			}
		}
	}
	
	public partial class List_UserQuestionsNotInQuizResult
	{
		
		private long _QuestionID;
		
		private string _Question;
		
		private System.Nullable<long> _AssetID;
		
		public List_UserQuestionsNotInQuizResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionID", DbType="BigInt NOT NULL")]
		public long QuestionID
		{
			get
			{
				return this._QuestionID;
			}
			set
			{
				if ((this._QuestionID != value))
				{
					this._QuestionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetID", DbType="BigInt")]
		public System.Nullable<long> AssetID
		{
			get
			{
				return this._AssetID;
			}
			set
			{
				if ((this._AssetID != value))
				{
					this._AssetID = value;
				}
			}
		}
	}
	
	public partial class List_CourseQuizzesWithUserResultsResult
	{
		
		private long _RecordID;
		
		private long _QuizID;
		
		private string _Caption;
		
		private System.Nullable<int> _MaxScore;
		
		private System.Nullable<int> _YourScore;
		
		private System.Nullable<System.DateTime> _CRTime;
		
		public List_CourseQuizzesWithUserResultsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="BigInt NOT NULL")]
		public long RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt NOT NULL")]
		public long QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Int")]
		public System.Nullable<int> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YourScore", DbType="Int")]
		public System.Nullable<int> YourScore
		{
			get
			{
				return this._YourScore;
			}
			set
			{
				if ((this._YourScore != value))
				{
					this._YourScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_UserSubscribedCoursesResult
	{
		
		private long _SubscriptionID;
		
		private long _CourseID;
		
		private System.Nullable<bool> _IsExpired;
		
		private string _Slug;
		
		private string _Icon;
		
		private string _Caption;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		public List_UserSubscribedCoursesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionID", DbType="BigInt NOT NULL")]
		public long SubscriptionID
		{
			get
			{
				return this._SubscriptionID;
			}
			set
			{
				if ((this._SubscriptionID != value))
				{
					this._SubscriptionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsExpired", DbType="Bit")]
		public System.Nullable<bool> IsExpired
		{
			get
			{
				return this._IsExpired;
			}
			set
			{
				if ((this._IsExpired != value))
				{
					this._IsExpired = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slug", DbType="VarChar(100)")]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this._Slug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(500)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this._Icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
	}
	
	public partial class List_QuizzesAllowedForUserResult
	{
		
		private long _QuizID;
		
		private string _Caption;
		
		private long _CourseID;
		
		private string _Slug;
		
		private string _CourseCaption;
		
		private System.Nullable<int> _MaxScore;
		
		private System.Nullable<int> _YourScore;
		
		private System.Nullable<System.DateTime> _PassDate;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		public List_QuizzesAllowedForUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuizID", DbType="BigInt NOT NULL")]
		public long QuizID
		{
			get
			{
				return this._QuizID;
			}
			set
			{
				if ((this._QuizID != value))
				{
					this._QuizID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slug", DbType="VarChar(100)")]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this._Slug = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseCaption", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string CourseCaption
		{
			get
			{
				return this._CourseCaption;
			}
			set
			{
				if ((this._CourseCaption != value))
				{
					this._CourseCaption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxScore", DbType="Int")]
		public System.Nullable<int> MaxScore
		{
			get
			{
				return this._MaxScore;
			}
			set
			{
				if ((this._MaxScore != value))
				{
					this._MaxScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YourScore", DbType="Int")]
		public System.Nullable<int> YourScore
		{
			get
			{
				return this._YourScore;
			}
			set
			{
				if ((this._YourScore != value))
				{
					this._YourScore = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PassDate
		{
			get
			{
				return this._PassDate;
			}
			set
			{
				if ((this._PassDate != value))
				{
					this._PassDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
	}
	
	public partial class List_UserCourseSubscriptionHistoryResult
	{
		
		private long _SubscriptionID;
		
		private long _UserID;
		
		private string _FullName;
		
		private long _CourseID;
		
		private string _Course;
		
		private System.Nullable<int> _Type;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private System.DateTime _CRTime;
		
		public List_UserCourseSubscriptionHistoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionID", DbType="BigInt NOT NULL")]
		public long SubscriptionID
		{
			get
			{
				return this._SubscriptionID;
			}
			set
			{
				if ((this._SubscriptionID != value))
				{
					this._SubscriptionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt NOT NULL")]
		public long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(401)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_UserCourseRecentSubscriptionsResult
	{
		
		private long _RecordID;
		
		private long _SubscriptionID;
		
		private long _UserID;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		private string _Email;
		
		private long _CourseID;
		
		private string _Course;
		
		private System.Nullable<int> _Type;
		
		private string _TypeCode;
		
		private System.Nullable<System.DateTime> _ExpDate;
		
		private System.DateTime _CRTime;
		
		public List_UserCourseRecentSubscriptionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecordID", DbType="BigInt NOT NULL")]
		public long RecordID
		{
			get
			{
				return this._RecordID;
			}
			set
			{
				if ((this._RecordID != value))
				{
					this._RecordID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriptionID", DbType="BigInt NOT NULL")]
		public long SubscriptionID
		{
			get
			{
				return this._SubscriptionID;
			}
			set
			{
				if ((this._SubscriptionID != value))
				{
					this._SubscriptionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt NOT NULL")]
		public long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseID", DbType="BigInt NOT NULL")]
		public long CourseID
		{
			get
			{
				return this._CourseID;
			}
			set
			{
				if ((this._CourseID != value))
				{
					this._CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeCode", DbType="NVarChar(200)")]
		public string TypeCode
		{
			get
			{
				return this._TypeCode;
			}
			set
			{
				if ((this._TypeCode != value))
				{
					this._TypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpDate
		{
			get
			{
				return this._ExpDate;
			}
			set
			{
				if ((this._ExpDate != value))
				{
					this._ExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
