#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Fractal")]
	public partial class DBUMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBUMDataContext() : 
				base(global::DB.Properties.Settings.Default.FractalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBUMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBUMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBUMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBUMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_UM")]
		public int tx_UM([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_tsp_stUsers")]
		public int UM_tsp_stUsers(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] ref System.Nullable<long> userID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(50)")] string username, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(200)")] string password, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="NVarChar(200)")] string fname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="NVarChar(200)")] string lname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BirthDate", DbType="Date")] System.Nullable<System.DateTime> birthDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="VarChar(100)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address1", DbType="NVarChar(200)")] string address1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address2", DbType="NVarChar(200)")] string address2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="State", DbType="Int")] System.Nullable<int> state, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Zip", DbType="VarChar(10)")] string zip, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="City", DbType="NVarChar(200)")] string city, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Avatar", DbType="NVarChar(200)")] string avatar, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="About", DbType="NVarChar(MAX)")] string about, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DefaultSubjectID", DbType="Int")] System.Nullable<int> defaultSubjectID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CollegeID", DbType="Int")] System.Nullable<int> collegeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="Bit")] System.Nullable<bool> gender)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, userID, username, password, fname, lname, birthDate, mobile, email, address1, address2, state, zip, city, avatar, about, defaultSubjectID, collegeID, isActive, gender);
			userID = ((System.Nullable<long>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_Authenticate")]
		public int UM_Authenticate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(100)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(200)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] ref System.Xml.Linq.XElement x)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password, x);
			x = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_tsp_stActions")]
		public int UM_tsp_stActions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionID", DbType="Int")] ref System.Nullable<int> permissionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(100)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AspxPagePath", DbType="NVarChar(100)")] string aspxPagePath, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ControlID", DbType="VarChar(100)")] string controlID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(50)")] string code, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionCode", DbType="VarChar(40)")] string permissionCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DCode", DbType="Int")] System.Nullable<int> dCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Icon", DbType="NVarChar(100)")] string icon, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortVal", DbType="Int")] System.Nullable<int> sortVal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IncludesHelp", DbType="Bit")] System.Nullable<bool> includesHelp, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HelpUrl", DbType="NVarChar(500)")] string helpUrl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, permissionID, caption, aspxPagePath, controlID, parentID, code, permissionCode, dCode, icon, sortVal, includesHelp, helpUrl);
			permissionID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_tsp_stRoles")]
		public int UM_tsp_stRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="Int")] ref System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(50)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="TinyInt")] System.Nullable<byte> code)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, roleID, caption, code);
			roleID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tx_stUsers")]
		public int tx_stUsers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement x, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="out", DbType="Xml")] ref System.Xml.Linq.XElement @out)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, x, @out);
			@out = ((System.Xml.Linq.XElement)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_Users", IsComposable=true)]
		public IQueryable<UM_List_UsersResult> UM_List_Users()
		{
			return this.CreateMethodCallQuery<UM_List_UsersResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_UserRoles", IsComposable=true)]
		public IQueryable<UM_List_UserRolesResult> UM_List_UserRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID)
		{
			return this.CreateMethodCallQuery<UM_List_UserRolesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_UserPermissions", IsComposable=true)]
		public IQueryable<UM_List_UserPermissionsResult> UM_List_UserPermissions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID)
		{
			return this.CreateMethodCallQuery<UM_List_UserPermissionsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_RoleUsers", IsComposable=true)]
		public IQueryable<UM_List_RoleUsersResult> UM_List_RoleUsers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="Int")] System.Nullable<int> roleID)
		{
			return this.CreateMethodCallQuery<UM_List_RoleUsersResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_Roles", IsComposable=true)]
		public IQueryable<UM_List_RolesResult> UM_List_Roles()
		{
			return this.CreateMethodCallQuery<UM_List_RolesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_RolePermissions", IsComposable=true)]
		public IQueryable<UM_List_RolePermissionsResult> UM_List_RolePermissions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="Int")] System.Nullable<int> roleID)
		{
			return this.CreateMethodCallQuery<UM_List_RolePermissionsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_PermissionUsers", IsComposable=true)]
		public IQueryable<UM_List_PermissionUsersResult> UM_List_PermissionUsers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionID", DbType="Int")] System.Nullable<int> permissionID)
		{
			return this.CreateMethodCallQuery<UM_List_PermissionUsersResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), permissionID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_Permissions", IsComposable=true)]
		public IQueryable<UM_List_PermissionsResult> UM_List_Permissions([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dcode)
		{
			return this.CreateMethodCallQuery<UM_List_PermissionsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dcode);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_List_PermissionRoles", IsComposable=true)]
		public IQueryable<UM_List_PermissionRolesResult> UM_List_PermissionRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PermissionID", DbType="Int")] System.Nullable<int> permissionID)
		{
			return this.CreateMethodCallQuery<UM_List_PermissionRolesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), permissionID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsEmailUniq", IsComposable=true)]
		public System.Nullable<bool> IsEmailUniq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, userID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.IsUsernameUniq", IsComposable=true)]
		public System.Nullable<bool> IsUsernameUniq([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="NVarChar(100)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, userID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UM_GetSingleUser", IsComposable=true)]
		public System.Xml.Linq.XElement UM_GetSingleUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="BigInt")] System.Nullable<long> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Slug", DbType="VarChar(100)")] string slug)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, slug).ReturnValue));
		}
	}
	
	public partial class UM_List_UsersResult
	{
		
		private long _usersid;
		
		private string _Username;
		
		private string _Password;
		
		private string _Fname;
		
		private string _Lname;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private string _Mobile;
		
		private string _Email;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Avatar;
		
		private System.Nullable<System.DateTime> _LastVisitDate;
		
		private long _VisitCount;
		
		private bool _IsActive;
		
		private System.Guid _unid;
		
		private System.DateTime _CRTime;
		
		public UM_List_UsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usersid", DbType="BigInt NOT NULL")]
		public long usersid
		{
			get
			{
				return this._usersid;
			}
			set
			{
				if ((this._usersid != value))
				{
					this._usersid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(200)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="Date")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this._BirthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(100)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(200)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this._Address1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(200)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this._Address2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Avatar", DbType="NVarChar(200)")]
		public string Avatar
		{
			get
			{
				return this._Avatar;
			}
			set
			{
				if ((this._Avatar != value))
				{
					this._Avatar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastVisitDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastVisitDate
		{
			get
			{
				return this._LastVisitDate;
			}
			set
			{
				if ((this._LastVisitDate != value))
				{
					this._LastVisitDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VisitCount", DbType="BigInt NOT NULL")]
		public long VisitCount
		{
			get
			{
				return this._VisitCount;
			}
			set
			{
				if ((this._VisitCount != value))
				{
					this._VisitCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid unid
		{
			get
			{
				return this._unid;
			}
			set
			{
				if ((this._unid != value))
				{
					this._unid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class UM_List_UserRolesResult
	{
		
		private int _RoleID;
		
		private string _Caption;
		
		private byte _Code;
		
		public UM_List_UserRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="TinyInt NOT NULL")]
		public byte Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
	}
	
	public partial class UM_List_UserPermissionsResult
	{
		
		private int _PermissionID;
		
		private System.Nullable<int> _ParentID;
		
		private string _Caption;
		
		private string _AspxPagePath;
		
		private string _ControlID;
		
		private string _Code;
		
		private string _PermissionCode;
		
		private System.Nullable<short> _Level;
		
		private string _Hierarchy;
		
		private string _Icon;
		
		private int _SortVal;
		
		private bool _IncludesHelp;
		
		private string _HelpUrl;
		
		public UM_List_UserPermissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionID", DbType="Int NOT NULL")]
		public int PermissionID
		{
			get
			{
				return this._PermissionID;
			}
			set
			{
				if ((this._PermissionID != value))
				{
					this._PermissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspxPagePath", DbType="NVarChar(100)")]
		public string AspxPagePath
		{
			get
			{
				return this._AspxPagePath;
			}
			set
			{
				if ((this._AspxPagePath != value))
				{
					this._AspxPagePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControlID", DbType="VarChar(100)")]
		public string ControlID
		{
			get
			{
				return this._ControlID;
			}
			set
			{
				if ((this._ControlID != value))
				{
					this._ControlID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionCode", DbType="VarChar(40)")]
		public string PermissionCode
		{
			get
			{
				return this._PermissionCode;
			}
			set
			{
				if ((this._PermissionCode != value))
				{
					this._PermissionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="SmallInt")]
		public System.Nullable<short> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hierarchy", DbType="VarChar(120)")]
		public string Hierarchy
		{
			get
			{
				return this._Hierarchy;
			}
			set
			{
				if ((this._Hierarchy != value))
				{
					this._Hierarchy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(100)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this._Icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortVal", DbType="Int NOT NULL")]
		public int SortVal
		{
			get
			{
				return this._SortVal;
			}
			set
			{
				if ((this._SortVal != value))
				{
					this._SortVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludesHelp", DbType="Bit NOT NULL")]
		public bool IncludesHelp
		{
			get
			{
				return this._IncludesHelp;
			}
			set
			{
				if ((this._IncludesHelp != value))
				{
					this._IncludesHelp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpUrl", DbType="NVarChar(500)")]
		public string HelpUrl
		{
			get
			{
				return this._HelpUrl;
			}
			set
			{
				if ((this._HelpUrl != value))
				{
					this._HelpUrl = value;
				}
			}
		}
	}
	
	public partial class UM_List_RoleUsersResult
	{
		
		private long _UserID;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		private string _Fullname;
		
		public UM_List_RoleUsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="BigInt NOT NULL")]
		public long UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(401)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
	}
	
	public partial class UM_List_RolesResult
	{
		
		private int _RoleID;
		
		private string _Caption;
		
		private byte _Code;
		
		public UM_List_RolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="TinyInt NOT NULL")]
		public byte Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
	}
	
	public partial class UM_List_RolePermissionsResult
	{
		
		private int _PermissionID;
		
		private System.Nullable<int> _ParentID;
		
		private string _Caption;
		
		private string _AspxPagePath;
		
		private string _ControlID;
		
		private string _Code;
		
		private string _PermissionCode;
		
		public UM_List_RolePermissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionID", DbType="Int NOT NULL")]
		public int PermissionID
		{
			get
			{
				return this._PermissionID;
			}
			set
			{
				if ((this._PermissionID != value))
				{
					this._PermissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspxPagePath", DbType="NVarChar(100)")]
		public string AspxPagePath
		{
			get
			{
				return this._AspxPagePath;
			}
			set
			{
				if ((this._AspxPagePath != value))
				{
					this._AspxPagePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControlID", DbType="VarChar(100)")]
		public string ControlID
		{
			get
			{
				return this._ControlID;
			}
			set
			{
				if ((this._ControlID != value))
				{
					this._ControlID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionCode", DbType="VarChar(40)")]
		public string PermissionCode
		{
			get
			{
				return this._PermissionCode;
			}
			set
			{
				if ((this._PermissionCode != value))
				{
					this._PermissionCode = value;
				}
			}
		}
	}
	
	public partial class UM_List_PermissionUsersResult
	{
		
		private int _UserID;
		
		private string _Username;
		
		private string _Fname;
		
		private string _Lname;
		
		private string _Fullname;
		
		public UM_List_PermissionUsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this._Username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(200)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(200)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fullname", DbType="NVarChar(401)")]
		public string Fullname
		{
			get
			{
				return this._Fullname;
			}
			set
			{
				if ((this._Fullname != value))
				{
					this._Fullname = value;
				}
			}
		}
	}
	
	public partial class UM_List_PermissionsResult
	{
		
		private int _PermissionID;
		
		private string _Caption;
		
		private string _AspxPagePath;
		
		private string _ControlID;
		
		private System.Nullable<int> _ParentID;
		
		private System.Nullable<short> _Level;
		
		private string _Hierarchy;
		
		private string _Code;
		
		private string _PermissionCode;
		
		private System.Nullable<int> _DCode;
		
		private string _Icon;
		
		private int _SortVal;
		
		private System.Nullable<System.DateTime> _CRTime;
		
		private bool _IncludesHelp;
		
		private string _HelpUrl;
		
		public UM_List_PermissionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionID", DbType="Int NOT NULL")]
		public int PermissionID
		{
			get
			{
				return this._PermissionID;
			}
			set
			{
				if ((this._PermissionID != value))
				{
					this._PermissionID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AspxPagePath", DbType="NVarChar(100)")]
		public string AspxPagePath
		{
			get
			{
				return this._AspxPagePath;
			}
			set
			{
				if ((this._AspxPagePath != value))
				{
					this._AspxPagePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ControlID", DbType="VarChar(100)")]
		public string ControlID
		{
			get
			{
				return this._ControlID;
			}
			set
			{
				if ((this._ControlID != value))
				{
					this._ControlID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="SmallInt")]
		public System.Nullable<short> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hierarchy", DbType="VarChar(120)")]
		public string Hierarchy
		{
			get
			{
				return this._Hierarchy;
			}
			set
			{
				if ((this._Hierarchy != value))
				{
					this._Hierarchy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermissionCode", DbType="VarChar(40)")]
		public string PermissionCode
		{
			get
			{
				return this._PermissionCode;
			}
			set
			{
				if ((this._PermissionCode != value))
				{
					this._PermissionCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCode", DbType="Int")]
		public System.Nullable<int> DCode
		{
			get
			{
				return this._DCode;
			}
			set
			{
				if ((this._DCode != value))
				{
					this._DCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(100)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this._Icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortVal", DbType="Int NOT NULL")]
		public int SortVal
		{
			get
			{
				return this._SortVal;
			}
			set
			{
				if ((this._SortVal != value))
				{
					this._SortVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludesHelp", DbType="Bit NOT NULL")]
		public bool IncludesHelp
		{
			get
			{
				return this._IncludesHelp;
			}
			set
			{
				if ((this._IncludesHelp != value))
				{
					this._IncludesHelp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HelpUrl", DbType="NVarChar(500)")]
		public string HelpUrl
		{
			get
			{
				return this._HelpUrl;
			}
			set
			{
				if ((this._HelpUrl != value))
				{
					this._HelpUrl = value;
				}
			}
		}
	}
	
	public partial class UM_List_PermissionRolesResult
	{
		
		private int _RoleID;
		
		private string _Caption;
		
		private byte _Code;
		
		public UM_List_PermissionRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int NOT NULL")]
		public int RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="TinyInt NOT NULL")]
		public byte Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
