//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class administration_CM_quiz {
    
    /// <summary>
    /// QuizMakerControl1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::plugins_QuizMaker_QuizMakerControl QuizMakerControl1;
    
    /// <summary>
    /// Master property.
    /// </summary>
    /// <remarks>
    /// Auto-generated property.
    /// </remarks>
    public new administration_MasterPage Master {
        get {
            return ((administration_MasterPage)(base.Master));
        }
    }
}
